import fonts from "./fonts";
import { Typography } from "./typography";

export const accessibleTypography: Typography = {
    paragraph: {
        sm1: {fontSize: '14', fontWeight: '400', fontFamily: fonts.regular},
        sm2: {fontSize: '16', fontWeight: '400', fontFamily: fonts.regular},
        sm3: {fontSize: '18', fontWeight: '400', fontFamily: fonts.regular},
        sm4: {fontSize: '20', fontWeight: '400', fontFamily: fonts.regular},
        sm5: {fontSize: '24', fontWeight: '400', fontFamily: fonts.regular},
        r1: {fontSize: '14', fontWeight: '400', fontFamily: fonts.regular},
        r2: {fontSize: '16', fontWeight: '400', fontFamily: fonts.regular},
        r3: {fontSize: '18', fontWeight: '400', fontFamily: fonts.regular},
        r4: {fontSize: '21', fontWeight: '400', fontFamily: fonts.regular},
        r5: {fontSize: '20', fontWeight: '400', fontFamily: fonts.regular},
        sb1: {fontSize: '14', fontWeight: '600', fontFamily: fonts.semiBold},
        sb2: {fontSize: '16', fontWeight: '600', fontFamily: fonts.semiBold},
        sb3: {fontSize: '18', fontWeight: '600', fontFamily: fonts.semiBold},
        sb4: {fontSize: '20', fontWeight: '600', fontFamily: fonts.semiBold},
        sb5: {fontSize: '24', fontWeight: '600', fontFamily: fonts.semiBold},
        b1: {fontSize: '14', fontWeight: '700', fontFamily: fonts.bold},
        b2: {fontSize: '16', fontWeight: '700', fontFamily: fonts.bold},
        b3: {fontSize: '18', fontWeight: '700', fontFamily: fonts.bold},
        b4: {fontSize: '20', fontWeight: '700', fontFamily: fonts.bold},
        b5: {fontSize: '24', fontWeight: '700', fontFamily: fonts.bold},
        m0: {fontSize: '12', fontWeight: '500', fontFamily: fonts.medium},
        m1: {fontSize: '14', fontWeight: '500', fontFamily: fonts.medium},
        m2: {fontSize: '16', fontWeight: '500', fontFamily: fonts.medium},
        m3: {fontSize: '18', fontWeight: '500', fontFamily: fonts.medium},
        m4: {fontSize: '20', fontWeight: '500', fontFamily: fonts.medium},
        m5: {fontSize: '24', fontWeight: '500', fontFamily: fonts.medium},
    },
    title: {
        h1: { fontSize: '32', fontWeight: '400', fontFamily: fonts.regular },
        h2: { fontSize: '28', fontWeight: '400', fontFamily: fonts.regular },
        h3: { fontSize: '24', fontWeight: '400', fontFamily: fonts.regular },
        h4: { fontSize: '24', fontWeight: '400', fontFamily: fonts.regular },
        h5: { fontSize: '20', fontWeight: '400', fontFamily: fonts.regular },
        b1: { fontSize: '38', fontWeight: '700', fontFamily: fonts.bold },
        b2: { fontSize: '28', fontWeight: '700', fontFamily: fonts.bold },
        b3: { fontSize: '24', fontWeight: '700', fontFamily: fonts.bold },
        b4: { fontSize: '24', fontWeight: '700', fontFamily: fonts.bold },
        sb1: { fontSize: '32', fontWeight: '600', fontFamily: fonts.semiBold },
        sb2: { fontSize: '28', fontWeight: '600', fontFamily: fonts.semiBold },
        sb3: { fontSize: '24', fontWeight: '600', fontFamily: fonts.semiBold },
        sb4: { fontSize: '24', fontWeight: '600', fontFamily: fonts.semiBold },
        sb5: { fontSize: '20', fontWeight: '600', fontFamily: fonts.semiBold },
        m1: { fontSize: '32', fontWeight: '500', fontFamily: fonts.medium },
        m2: { fontSize: '28', fontWeight: '500', fontFamily: fonts.medium },
        m3: { fontSize: '24', fontWeight: '500', fontFamily: fonts.medium },
        m4: { fontSize: '24', fontWeight: '500', fontFamily: fonts.medium },
        m5: { fontSize: '20', fontWeight: '500', fontFamily: fonts.medium },
        b5: { fontSize: '20', fontWeight: '500', fontFamily: fonts.medium },
    }
}